import yaml
F_PATH_ADMIN_QUERIES = 'config_files\\queries_base_admin.yml'

class QueriesAdmin:
    """
    Maintains all the config variables
    """
    @classmethod
    def load(cls):
        with open(F_PATH_ADMIN_QUERIES, 'r') as f:
            data = yaml.safe_load(f)
            cls.QUERY_TO_ADD_IN_AUTH_TABLE = data['QUERY_TO_ADD_IN_AUTH_TABLE']
            cls.QUERY_TO_ADD_IN_EMP_DETAILS_TABLE = data['QUERY_TO_ADD_IN_EMP_DETAILS_TABLE']
            cls.QUERY_TO_ADD_SALARY = data['QUERY_TO_ADD_SALARY']
            cls.QUERY_TO_CALCULATE_LEAVES = data['QUERY_TO_CALCULATE_LEAVES']
            cls.QUERY_TO_CHECK_IF_DEFAULT_PASWORD = data['QUERY_TO_CHECK_IF_DEFAULT_PASWORD']
            cls.QUERY_TO_CHANGE_DEFAULT_PASWORD = data['QUERY_TO_CHANGE_DEFAULT_PASWORD']
            cls.QUERY_FOR_CREATE_AUTH_TABLE = data['QUERY_FOR_CREATE_AUTH_TABLE']
            cls.QUERY_FOR_CREATE_EMP_DETAILS_TABLE = data['QUERY_FOR_CREATE_EMP_DETAILS_TABLE']
            cls.QUERY_FOR_CREATE_LEAVES_TABLE = data['QUERY_FOR_CREATE_LEAVES_TABLE']
            cls.QUERY_FOR_CREATE_SALARY_TABLE = data['QUERY_FOR_CREATE_SALARY_TABLE']
            cls.QUERY_TO_DELETE_FROM_AUTH_TABLE = data['QUERY_TO_DELETE_FROM_AUTH_TABLE']
            cls.QUERY_TO_DELETE_FROM_EMPLOYEE_TABLE = data['QUERY_TO_DELETE_FROM_EMPLOYEE_TABLE']
            cls.QUERY_TO_DISPLAY_EMPLOYEE_DETAILS = data['QUERY_TO_DISPLAY_EMPLOYEE_DETAILS']
            cls.QUERY_TO_DISPLAY_LEAVES_DETAILS = data['QUERY_TO_DISPLAY_LEAVES_DETAILS']           
            cls.QUERY_TO_DISPLAY_SALARY_DETAILS = data['QUERY_TO_DISPLAY_SALARY_DETAILS']
            cls.LIST_TO_DISPLAY_EMPLOYEE_DETAILS = data['LIST_TO_DISPLAY_EMPLOYEE_DETAILS']
            cls.LIST_TO_DISPLAY_LEAVES_DETAILS = data['LIST_TO_DISPLAY_LEAVES_DETAILS']
            cls.LIST_TO_DISPLAY_SALARY_DETAILS = data['LIST_TO_DISPLAY_SALARY_DETAILS']         
            cls.QUERY_TO_ENABLE_FOREIGN_KEY = data['QUERY_TO_ENABLE_FOREIGN_KEY'] 
            cls.QUERY_TO_UPDATE_LEAVES_STATUS = data['QUERY_TO_UPDATE_LEAVES_STATUS']           
            cls.QUERY_TO_VERIFY_LOGIN = data['QUERY_TO_VERIFY_LOGIN']
